// Interface Profissional v3 - camada visual e operacional sem alterar regras-base.
state.ui=state.ui||{};
state.ui.filters=state.ui.filters||{};
state.ui.sorts=state.ui.sorts||{};
state.productImages=state.productImages||{};

function puiCategory(name){const n=norm(name);if(/watch|buds|fit/.test(n))return 'Wearables';if(/fold|flip|\ba\d|\bs\d|smartphone|celular/.test(n))return 'Smartphones';return 'Acessórios'}
function puiImgId(p){return p?invId(p):''}
function puiThumb(p,label='Produto'){const id=puiImgId(p),url=id&&state.productImages[id];const initials=String((p&&p.name)||label).replace(/galaxy|samsung/ig,'').trim().split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toUpperCase()||'P';return `<div class="product-thumb ${url?'':'photo-missing'}">${url?`<img src="${String(url).replace(/"/g,'&quot;')}" alt="">`:initials}</div>`}
function puiProductCell(p,name,sub=''){return `<div class="product-cell">${puiThumb(p,name)}<div class="product-main"><strong>${name}</strong>${sub?`<span class="muted">${sub}</span>`:''}</div></div>`}
function puiProgress(done,total){const pct=total?Math.max(0,Math.min(100,Math.round(done/total*100))):0,cls=pct>=100?'':pct>=60?'warn':'bad';return `<div class="progress-wrap"><div class="progress-meta"><span>${done}/${total}</span><b>${pct}%</b></div><div class="progress ${cls}"><i style="width:${pct}%"></i></div></div>`}
function puiSort(list,key,dir='desc'){return [...list].sort((a,b)=>{let A=typeof key==='function'?key(a):a[key],B=typeof key==='function'?key(b):b[key];if(typeof A==='string'||typeof B==='string')return String(A||'').localeCompare(String(B||''),'pt-BR',{numeric:true})*(dir==='asc'?1:-1);return ((Number(A)||0)-(Number(B)||0))*(dir==='asc'?1:-1)})}
function puiQuick(containerId,items,current,onClick){const root=document.getElementById(containerId);if(!root)return;root.innerHTML=items.map(x=>`<button class="quick-chip ${current===x[0]?'active':''}" data-v="${x[0]}">${x[1]}</button>`).join('');root.querySelectorAll('button').forEach(b=>b.onclick=()=>onClick(b.dataset.v))}
function puiEnsure(id,html,before){if(document.getElementById(id))return;const el=document.createElement('div');el.id=id;el.innerHTML=html;before.parentNode.insertBefore(el,before)}
function puiTableSummary(id,shown,total,label='itens'){return `<div class="table-summary"><span>Mostrando <b>${shown}</b> de <b>${total}</b> ${label}</span><span>Use filtros e ordenação para refinar a análise.</span></div>`}
function puiEditImage(id){const p=state.inventory.find(x=>invId(x)===id);if(!p)return;const cur=state.productImages[id]||'';const val=prompt(`Imagem de ${p.name}\n\nCole uma URL de imagem. Deixe vazio para remover.`,cur);if(val===null)return;const clean=val.trim();if(clean)state.productImages[id]=clean;else delete state.productImages[id];save()}
window.editProductImage=puiEditImage;

function puiSetup(){
 document.body.classList.add('professional-v3');
 const brand=document.querySelector('.brand b');if(brand&&!document.querySelector('.professional-tag'))brand.insertAdjacentHTML('afterend','<span class="professional-tag">Pro</span>');
 const overviewPanel=document.querySelector('#view-overview .panel');if(overviewPanel){puiEnsure('overviewQuick','<div class="quick-filters"></div>',overviewPanel);puiEnsure('attentionPanel','',overviewPanel)}
 const productsPanel=document.querySelector('#view-products .panel');if(productsPanel)puiEnsure('productsQuick','<div class="quick-filters"></div>',productsPanel);
 const portfolioPanel=document.querySelector('#view-portfolio .panel');if(portfolioPanel)puiEnsure('portfolioQuick','<div class="quick-filters"></div>',portfolioPanel);
 const prePanel=document.querySelector('#view-presales .panel');if(prePanel)puiEnsure('preQuick','<div class="quick-filters"></div>',prePanel);
 const reqPanel=document.querySelector('#view-requests .panel');if(reqPanel){const t=reqPanel.querySelector('#requestsTable');puiEnsure('requestsToolbar','<div class="toolbar"><input id="requestSearch" class="input search" placeholder="Buscar produto ou filial"><select id="requestStore" class="select"><option value="all">Todas as filiais</option></select><select id="requestSort" class="select sort-select"><option value="qty-desc">Maior quantidade</option><option value="qty-asc">Menor quantidade</option><option value="name-asc">Produto A–Z</option></select></div><div id="requestsQuick" class="quick-filters" style="padding:12px 14px 0"></div>',t)}
 function addSort(toolbarId,selectId,options){const tb=document.querySelector(toolbarId);if(tb&&!document.getElementById(selectId)){const s=document.createElement('select');s.id=selectId;s.className='select sort-select';s.innerHTML=options;tb.appendChild(s)}}
 addSort('#view-overview .toolbar','overviewSort','<option value="stock-desc">Maior saldo</option><option value="stock-asc">Menor saldo</option><option value="name-asc">Produto A–Z</option><option value="name-desc">Produto Z–A</option>');
 addSort('#view-products .toolbar','productSort','<option value="stock-desc">Maior saldo</option><option value="stock-asc">Menor saldo</option><option value="name-asc">Produto A–Z</option><option value="name-desc">Produto Z–A</option>');
 addSort('#view-portfolio .toolbar','portfolioSort','<option value="need-desc">Maior falta primeiro</option><option value="stock-asc">Menor saldo</option><option value="stock-desc">Maior saldo</option><option value="name-asc">Produto A–Z</option>');
 addSort('#view-presales .toolbar','preSort','<option value="deficit-desc">Maior déficit primeiro</option><option value="count-desc">Mais pré-vendas</option><option value="stock-asc">Menor estoque</option><option value="name-asc">Produto A–Z</option>');
 ['overviewSort','productSort','portfolioSort','preSort','requestSort'].forEach(id=>{const e=document.getElementById(id);if(e)e.onchange=()=>renderAll()});
 ['requestSearch'].forEach(id=>{const e=document.getElementById(id);if(e)e.oninput=()=>renderRequests()});const rs=document.getElementById('requestStore');if(rs)rs.onchange=()=>renderRequests();
}

const puiBaseOverview=renderOverview;
renderOverview=function(){
 const inv=activeInventory(),low=inv.filter(p=>p.stock<=state.minStock),zero=inv.filter(p=>p.stock<=0),units=inv.reduce((s,p)=>s+p.stock,0),val=inv.reduce((s,p)=>s+p.subtotal,0);
 $('#overviewCards').innerHTML=card('Produtos ativos',inv.length,'base operacional')+card('Unidades em loja',units.toLocaleString('pt-BR'),'saldo físico')+card('Estoque baixo',low.length,`até ${state.minStock} unidades`,'red')+card('Valor em estoque',brMoney(val),'valor a custo');
 const port=typeof portfolioAnalysis==='function'?portfolioAnalysis():[],pa=typeof preAnalysis==='function'?preAnalysis():[];
 const portMissing=port.filter(x=>x.status==='missing').length,preDef=pa.reduce((s,x)=>s+x.deficit,0),un=pa.filter(x=>x.status==='unlinked').length;
 const att=document.getElementById('attentionPanel');if(att)att.innerHTML=`<div class="attention-panel"><div class="attention-head"><h3>Atenção necessária</h3><span>Prioridades da operação agora</span></div><div class="attention-grid"><div class="attention-item ${zero.length?'danger':'ok'}"><b>${zero.length}</b><span>produtos zerados</span></div><div class="attention-item ${portMissing?'warn':'ok'}"><b>${portMissing}</b><span>itens de portfólio pendentes</span></div><div class="attention-item ${preDef?'danger':'ok'}"><b>${preDef}</b><span>unidades faltantes em pré-vendas</span></div><div class="attention-item ${un?'warn':'ok'}"><b>${un}</b><span>pré-vendas sem vínculo</span></div></div></div>`;
 state.ui.filters.overview=state.ui.filters.overview||'all';puiQuick('overviewQuick',[['all','Todos'],['low','Estoque baixo'],['zero','Zerados'],['good','Disponíveis']],state.ui.filters.overview,v=>{state.ui.filters.overview=v;renderOverview()});
 let q=norm($('#overviewSearch').value),quick=state.ui.filters.overview,st=$('#overviewStatus').value;let list=inv.filter(p=>(!q||norm(`${p.name} ${p.code} ${p.ref}`).includes(q))&&(st==='all'||(st==='low')===(p.stock<=state.minStock))&&(quick==='all'||quick==='low'&&p.stock<=state.minStock||quick==='zero'&&p.stock<=0||quick==='good'&&p.stock>state.minStock));
 const sort=$('#overviewSort')?.value||'stock-desc';if(sort==='stock-desc')list=puiSort(list,'stock','desc');if(sort==='stock-asc')list=puiSort(list,'stock','asc');if(sort==='name-asc')list=puiSort(list,'name','asc');if(sort==='name-desc')list=puiSort(list,'name','desc');
 $('#overviewTable').innerHTML=list.length?`<table class="mobile-cards"><thead><tr><th>Produto</th><th>Categoria</th><th>Estoque</th><th>Custo</th><th>Situação</th></tr></thead><tbody>${list.map(p=>`<tr><td data-label="Produto">${puiProductCell(p,p.name,`SKU ${p.code} · ${p.ref||'-'}`)}</td><td data-label="Categoria">${puiCategory(p.name)}</td><td data-label="Estoque" class="qty">${p.stock} un.</td><td data-label="Custo">${brMoney(p.unitCost)}</td><td data-label="Situação"><span class="status ${p.stock<=state.minStock?'bad':'good'}">● ${p.stock<=0?'Sem estoque':p.stock<=state.minStock?'Estoque baixo':'Disponível'}</span></td></tr>`).join('')}</tbody></table>${puiTableSummary('ov',list.length,inv.length,'produtos')}`:'<div class="empty"><b>Nenhum produto neste filtro</b>Altere os filtros para visualizar outros itens.</div>';
 $('#lowTable').innerHTML=low.length?`<table class="mobile-cards"><thead><tr><th>Produto</th><th>Saldo</th><th>Situação</th></tr></thead><tbody>${puiSort(low,'stock','asc').map(p=>`<tr><td data-label="Produto">${puiProductCell(p,p.name,`SKU ${p.code}`)}</td><td data-label="Saldo" class="qty">${p.stock}</td><td data-label="Situação"><span class="status bad">● ${p.stock<=0?'Sem estoque':'Baixo'}</span></td></tr>`).join('')}</tbody></table>`:'<div class="empty"><b>Nenhum item com estoque baixo</b>A operação está saudável.</div>';
};

renderProducts=function(){
 const all=state.inventory;state.ui.filters.products=state.ui.filters.products||'all';puiQuick('productsQuick',[['all','Todos'],['active','Ativos'],['disabled','Desativados'],['zero','Zerados'],['low','Estoque baixo']],state.ui.filters.products,v=>{state.ui.filters.products=v;renderProducts()});
 let q=norm($('#productSearch').value),fs=$('#productState').value,quick=state.ui.filters.products;let list=all.filter(p=>{const d=!!state.disabled[invId(p)];return (!q||norm(`${p.name} ${p.code} ${p.ref}`).includes(q))&&(fs==='all'||fs==='disabled'&&d||fs==='active'&&!d)&&(quick==='all'||quick==='active'&&!d||quick==='disabled'&&d||quick==='zero'&&p.stock<=0||quick==='low'&&!d&&p.stock<=state.minStock)});
 const sort=$('#productSort')?.value||'stock-desc';if(sort==='stock-desc')list=puiSort(list,'stock','desc');if(sort==='stock-asc')list=puiSort(list,'stock','asc');if(sort==='name-asc')list=puiSort(list,'name','asc');if(sort==='name-desc')list=puiSort(list,'name','desc');
 $('#productsTable').innerHTML=list.length?`<table class="mobile-cards"><thead><tr><th>Produto</th><th>Categoria</th><th>Estoque</th><th>Situação</th><th>Ações</th></tr></thead><tbody>${list.map(p=>{const d=!!state.disabled[invId(p)];return `<tr><td data-label="Produto">${puiProductCell(p,p.name,`SKU ${p.code} · ${p.ref||'-'}`)}</td><td data-label="Categoria">${puiCategory(p.name)}</td><td data-label="Estoque" class="qty">${p.stock} un.</td><td data-label="Situação"><span class="status ${d?'warn':p.stock<=state.minStock?'bad':'good'}">● ${d?'Desativado':p.stock<=0?'Sem estoque':p.stock<=state.minStock?'Baixo':'Disponível'}</span></td><td data-label="Ações"><div class="menu-actions"><button class="btn small secondary photo-btn" onclick="editProductImage('${invId(p).replace(/'/g,"\\'")}')">Imagem</button><button class="btn small ${d?'secondary':'danger'}" onclick="toggleDisabled('${invId(p).replace(/'/g,"\\'")}')">${d?'Reativar':'Desativar'}</button></div></td></tr>`}).join('')}</tbody></table>${puiTableSummary('pr',list.length,all.length,'produtos')}`:'<div class="empty"><b>Nenhum produto neste filtro</b>Altere a pesquisa ou os filtros.</div>';
};

const puiPortfolioAnalysis=portfolioAnalysis;
renderPortfolio=function(){
 const a=portfolioAnalysis(),required=a.reduce((s,x)=>s+x.min,0),covered=a.reduce((s,x)=>s+Math.min(x.stock,x.min),0),complete=a.filter(x=>x.status==='complete').length,missing=a.length-complete,cov=required?Math.round(covered/required*100):0;
 $('#portfolioCards').innerHTML=card('Conformidade',`${cov}%`,`${covered} de ${required} unidades`,cov<100?'amber':'')+card('Itens completos',complete,`de ${a.length} produtos`)+card('Itens pendentes',missing,'abaixo do mínimo',missing?'red':'')+card('Unidades necessárias',a.reduce((s,x)=>s+x.need,0),'para chegar a 100%',missing?'amber':'');$('#portfolioBadge').textContent=missing;
 state.ui.filters.portfolio=state.ui.filters.portfolio||'all';puiQuick('portfolioQuick',[['all','Todos'],['missing','Pendentes'],['zero','Zerados'],['complete','Completos']],state.ui.filters.portfolio,v=>{state.ui.filters.portfolio=v;renderPortfolio()});
 let q=norm($('#portfolioSearch').value),st=$('#portfolioStatus').value,cat=$('#portfolioCategory').value,quick=state.ui.filters.portfolio;let list=a.filter(x=>(!q||norm(x.name).includes(q))&&(st==='all'||x.status===st)&&(cat==='all'||x.category===cat)&&(quick==='all'||quick==='missing'&&x.status==='missing'||quick==='zero'&&x.stock<=0||quick==='complete'&&x.status==='complete'));
 const sort=$('#portfolioSort')?.value||'need-desc';if(sort==='need-desc')list=puiSort(list,'need','desc');if(sort==='stock-asc')list=puiSort(list,'stock','asc');if(sort==='stock-desc')list=puiSort(list,'stock','desc');if(sort==='name-asc')list=puiSort(list,'name','asc');
 $('#portfolioTable').innerHTML=list.length?`<table class="mobile-cards"><thead><tr><th>Produto obrigatório</th><th>Categoria</th><th>Cobertura</th><th>Saldo</th><th>Falta</th><th>Situação</th><th>Ação</th></tr></thead><tbody>${list.map(x=>{const p=x.matches?.[0]||null;return `<tr><td data-label="Produto">${puiProductCell(p,x.name,`${x.category}`)}</td><td data-label="Categoria">${x.category}</td><td data-label="Cobertura">${puiProgress(Math.min(x.stock,x.min),x.min)}</td><td data-label="Saldo" class="qty">${x.stock}</td><td data-label="Falta" class="qty">${x.need}</td><td data-label="Situação"><span class="status ${x.status==='complete'?'good':'bad'}">● ${x.status==='complete'?'Completo':x.stock<=0?'Sem estoque':`Faltam ${x.need}`}</span></td><td data-label="Ação"><div class="menu-actions"><button class="btn small secondary" onclick="openPortfolioLink('${x.id}')">Editar produto</button><button class="btn small danger" onclick="removePortfolioItem('${x.id}')">Excluir</button></div></td></tr>`}).join('')}</tbody></table>${puiTableSummary('po',list.length,a.length,'itens')}`:'<div class="empty"><b>Nenhum item neste filtro</b>Altere os filtros para visualizar outros produtos.</div>';
};

renderPre=function(){
 let a=preAnalysis(),total=state.preSales.length,covered=a.reduce((s,x)=>s+Math.min(x.count,x.stock),0),def=a.reduce((s,x)=>s+x.deficit,0),un=a.filter(x=>x.status==='unlinked').length,cov=total?Math.round(covered/total*100):0;
 $('#preCards').innerHTML=card('Pré-vendas',total,'reservas importadas')+card('Cobertura',`${cov}%`,`${covered} de ${total} unidades`,cov<100?'amber':'')+card('Unidades faltantes',def,'déficit total',def?'red':'')+card('Não vinculados',un,'precisam de revisão',un?'amber':'');
 state.ui.filters.pre=state.ui.filters.pre||'all';puiQuick('preQuick',[['all','Todas'],['partial','Com déficit'],['unlinked','Não vinculadas'],['good','Atendidas'],['zero','Sem estoque']],state.ui.filters.pre,v=>{state.ui.filters.pre=v;renderPre()});
 let q=norm($('#preSearch').value),st=$('#preStatus').value,quick=state.ui.filters.pre;let list=a.filter(x=>(!q||norm(`${x.product} ${x.capacity} ${x.color}`).includes(q))&&(st==='all'||x.status===st)&&(quick==='all'||quick==='partial'&&x.status==='partial'||quick==='unlinked'&&x.status==='unlinked'||quick==='good'&&x.status==='good'||quick==='zero'&&x.match&&x.stock<=0));
 const sort=$('#preSort')?.value||'deficit-desc';if(sort==='deficit-desc')list=puiSort(list,'deficit','desc');if(sort==='count-desc')list=puiSort(list,'count','desc');if(sort==='stock-asc')list=puiSort(list,'stock','asc');if(sort==='name-asc')list=puiSort(list,x=>`${x.product} ${x.capacity} ${x.color}`,'asc');
 $('#preTable').innerHTML=list.length?`<table class="mobile-cards"><thead><tr><th>Produto reservado</th><th>Pré-vendas</th><th>Cobertura</th><th>Estoque</th><th>Saldo livre</th><th>Situação</th><th>Ação</th></tr></thead><tbody>${list.map(x=>{const p=x.match?.p||null;const available=x.match?Math.min(x.count,x.stock):0;return `<tr><td data-label="Produto">${puiProductCell(p,`${x.product} ${x.capacity}`,x.color)}</td><td data-label="Pré-vendas" class="qty">${x.count}</td><td data-label="Cobertura">${puiProgress(available,x.count)}</td><td data-label="Estoque" class="qty">${x.match?x.stock:'—'}</td><td data-label="Saldo livre" class="qty">${x.match?x.free:'—'}</td><td data-label="Situação"><span class="status ${x.status==='good'?'good':x.status==='partial'?'bad':'warn'}">● ${x.status==='good'?'Atende':x.status==='partial'?(x.stock<=0?'Sem estoque':`Faltam ${x.deficit}`):'Não vinculado'}</span></td><td data-label="Ação"><div class="menu-actions"><button class="btn small secondary" onclick="openLink('${x.key.replace(/'/g,"\\'")}')">Editar vínculo</button>${x.deficit&&x.match?`<button class="btn small primary" onclick="requestFromPre('${x.key.replace(/'/g,"\\'")}')">Solicitar ${x.deficit}</button>`:''}</div></td></tr>`}).join('')}</tbody></table>${puiTableSummary('pv',list.length,a.length,'grupos de pré-venda')}`:`<div class="empty"><b>${total?'Nenhum item neste filtro':'Nenhuma pré-venda importada'}</b>${total?'Altere os filtros para visualizar outros itens.':'Importe o CSV de pré-vendas.'}</div>`;
};

renderRequests=function(){
 let r=state.requests||[];$('#reqBadge').textContent=r.length;const search=document.getElementById('requestSearch'),storeSel=document.getElementById('requestStore');if(storeSel){const cur=storeSel.value;const stores=[...new Set(r.map(x=>x.store).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'pt-BR'));storeSel.innerHTML='<option value="all">Todas as filiais</option>'+stores.map(s=>`<option value="${s.replace(/"/g,'&quot;')}">${s}</option>`).join('');if(stores.includes(cur))storeSel.value=cur}
 state.ui.filters.requests=state.ui.filters.requests||'all';puiQuick('requestsQuick',[['all','Todas'],['high','Maior necessidade'],['single','1 unidade'],['multi','2+ unidades']],state.ui.filters.requests,v=>{state.ui.filters.requests=v;renderRequests()});
 const q=norm(search?.value||''),sf=storeSel?.value||'all',quick=state.ui.filters.requests;let list=r.map((x,i)=>({...x,_i:i})).filter(x=>(!q||norm(`${x.name} ${x.store} ${x.ref}`).includes(q))&&(sf==='all'||x.store===sf)&&(quick==='all'||quick==='high'&&x.qty>=3||quick==='single'&&x.qty===1||quick==='multi'&&x.qty>=2));const sort=document.getElementById('requestSort')?.value||'qty-desc';if(sort==='qty-desc')list=puiSort(list,'qty','desc');if(sort==='qty-asc')list=puiSort(list,'qty','asc');if(sort==='name-asc')list=puiSort(list,'name','asc');
 $('#requestsTable').innerHTML=list.length?`<table class="mobile-cards"><thead><tr><th>Produto</th><th>Filial</th><th>Quantidade</th><th>Ações</th></tr></thead><tbody>${list.map(x=>{const p=state.inventory.find(p=>invId(p)===x.inventoryId);return `<tr><td data-label="Produto">${puiProductCell(p,x.name,x.ref||'')}</td><td data-label="Filial"><strong>${x.store}</strong></td><td data-label="Quantidade"><input class="input" style="width:76px" type="number" min="1" value="${x.qty}" onchange="setReqQty(${x._i},this.value)"></td><td data-label="Ações"><button class="btn small danger" onclick="removeReq(${x._i})">Remover</button></td></tr>`}).join('')}</tbody></table>${puiTableSummary('rq',list.length,r.length,'solicitações')}`:'<div class="empty"><b>Nenhuma solicitação neste filtro</b>Déficits de Pré-venda podem ser enviados para cá.</div>';
};

const puiOldRenderAll=renderAll;
renderAll=function(){puiSetup();state.minStock=Number($('#minStock')?.value??state.minStock)||0;$('#prodBadge').textContent=activeInventory().length;$('#lowBadge').textContent=activeInventory().filter(p=>p.stock<=state.minStock).length;$('#preBadge').textContent=state.preSales.length;$('#baseDate').textContent=state.inventoryDate?`Inventário ${new Date(state.inventoryDate).toLocaleDateString('pt-BR')}`:'Nenhum inventário';$('#preImportInfo').textContent=state.preImportDate?`${state.preSales.length} registros importados em ${new Date(state.preImportDate).toLocaleString('pt-BR')}`:'Nenhum relatório de pré-vendas importado.';renderOverview();renderProducts();renderPortfolio();renderPre();renderRequests()};

puiSetup();renderAll();
